# Site
repository: ssemi/ssemi.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 설세민 (Semin Seol)
title: .NET / C# 백엔드 개발자
email: semin.seol@gmail.com
website: https://www.ssemi.net

# Dark Mode (true/false/never)
darkmode: never

# Social links
github_username:  ssemi
linkedin_username: ssemi

# Additional icon links
#additional_links:
#- title: Ssemi's Blog
#  icon: fas fa-globe
#  url: https://www.ssemi.net
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | 
  .NET 과 C# 개발을 전문적으로 하고 있고, 이것저것 깔짝깔짝 거리기 좋아하고, AWS와 Azure 클라우드 기반의 백엔드 개발자<br/>
  <mark>개발</mark> 과 <mark>인프라</mark>의 중간에서 이도저도 아닌 느낌으로 DNA는 개발 6.5: 인프라3.5 정도??<br/>
  T자형 인재가 되고 싶은데, 현실은 ㅜ 의 느낌<br/>
  <br/>
  **사람이 읽기 좋은 코드**가 좋은 코드라는 것을 <mark>코드리뷰</mark> 때마다 설파하며 단순히 코드를 줄이는게 목적이 아닌 쓰임을 생각하는 개발자<br/>
  <mark>테스트</mark>를 열심히 하려고 하는 테린이 개발자<br/>
  재미 있어 보이는 토이 개발 같은 경우 NodeJS 나 Python 같은 언어들로 빠르게 만드는 것을 좋아합니다<br/>
  <br/>
  현재 회사에서 서비스 초기 아키텍쳐 설계, 셋업, 클라우드 보안, 인증 서버 담당, 백엔드 개발자 채용을 담당하고 있습니다<br/>
  하고 싶은 일들을 회사에다가 어떻게 하면 사용/개발/운영 할 수 있을까?를 고민하면서 최대한 해볼 수 있는 것들을 해보려고 합니다<br/>
  <br/>

content:
  - title: Experience 
    layout: list 
    content:
      - layout: left
        title: 클로버추얼패션
        link: https://www.clovirtualfashion.com
        link_text: clovirtualfashion.com
        sub_title: Web Backend Developer
        caption: 2013. 12 - 현재 (8y)
        quote: >
          3D 기반 시뮬레이션 프로그램으로 패션 업체를 선도하고 있는 기업
        description: | 
            - 글로벌 서비스 사이트 개발/운영
            - 라이선스/인보이스/정산 관련 백오피스 시스템 설계 및 개발
            - C/S Application 인증 서버 개발 (TCP Socket-> Web)
            - AWS, Azure 경험
            - 자동화 할 수 있는 것들은 다 자동화 하려고 함
            - 클라우드 보안 담당
            - 개발자 채용 담당
            - 코드리뷰 & 테스트 코드 & 아키텍처 개선 등 개발 환경 개선
      
      - layout: left
        title: 알서포트
        link: https://www.rsupport.com
        link_text: rsupport.com
        sub_title: Web Backend Developer
        caption: 2011.07 - 2012.10 (1y 4m)
        quote: >
          원격 제어 솔루션의 강자
        description: | 
            - 원격 제어 솔루션 RView 제품 개발/유지보수/서버 납품
            - 제품 리팩토링 작업 주도 (코드 개선 및 통합, 작업 환경 개선)
            - 다국 결제PG 개발 경험 (KCP, Paypal, Alipay, Epsilon)
            - C/S Application 통신하는 API 관련 개발 및 유지보수 (XML, SOAP)
            - 서버 납품 버전 업무를 맡아서 해외 지사들과의 커뮤니케이션
            - Application 서버납품을 위한 설치본 작업 (Install Shield)
      
      - layout: left
        title: HELPst
        link: https://ssemi.tistory.com/1644
        link_text: helpst.com
        sub_title: Cheif Technology Officer
        caption: 2010.06 - 2011.05 (1y)
        quote: >
          첫 창업의 경험
        description: | 
            - 온라인 고객센터의 Saas 서비스를 목표
            - 펀딩 받아서 진행 (스타트업)
            - 스타트업 - 벤처 체제의 3인 팀프로젝트 (기획자, 개발자, 디자이너)
            - 개발자 포지션으로 백지에서 기획, 개발, 운영, 마케팅까지 열정을 쏟아부음
            - 회사를 운영 한다는 것에 대한 여러가지 많은 것들을 배우게 되어서 매우 뜻깊은 경험
            - 그렇지만 실패했던 경험

      - layout: left
        title: 참좋은레져
        link: https://www.verygoodtour.com/
        link_text: verygoodtour.com
        sub_title: Web Developer
        caption: 2007.11 - 2009.12 (2y 2m)
        quote: >
          국내 Top-tier 여행사 참좋은여행
        description: | 
            - 참좋은여행 사이트 개발/유지보수
            - 참좋은레져 그룹웨어 개발 - 여행 사이트 연동 부분 담당
            - 참좋은레져 ERP 프로젝트 개발
            - 여행사 비지니스 도메인에 대한 이해

      - layout: left
        title: 엔토로
        sub_title: Web Developer
        caption: 2002.01 - 2005.08 (3y 8m)
        quote: >
          유아 교육 사이트 - 첫 직장에서의 개발자로서의 경험들
        description: | 
            - 자사 서비스 개발 및 유지보수
            - 유아 교육 사이트 (베베라인) / 플래시 게임 사이트 (조이월드)
            - 개발/결제/운영 등등 가입부터 결제까지 일련의 서비스 과정에 대한 내용을 모두 경험
            - 포털 업체들과 Contents Provider 로서의 경험 (네이버, 다음, 야후 등등)
  
  

  - title: Skill 
    layout: list 
    content:
      - layout: left
        title: Backend
        quote: >
          현재 업무에 사용중 혹은 사용했던 기술들입니다
        description: | 
            - .NET (2020~) | .NET Core (2017~) | .NET Framework (2009~)
            - C#, NodeJS, Python
            - MVC, Web API
            - MSSQL, MySQL, MongoDB, Redis, RabbitMQ
            - Entity Framework, Dapper
            - NUnit, MS Test
      - layout: left
        title: DevOps
        quote: >
          IDC 경험이 있으며, AWS를 더 오래 사용했고, 2021년부터 Azure 사용 중
        description: | 
            - Windows (IIS), Linux (Apache, Nginx)
            - Network Knowledge
            - AWS (2014~), Azure (2021~)
            - Teamcity, Github Action, AWS Code-*, Azure DevOps
            - Docker, Docker Compose, Kubernetes (AWS EKS, Azure AKS)
            - Terraform, Packer
      - layout: left
        title: Frontend
        quote: >
          (옛날 사람) jQuery 까지 개발 해보고, 그 이후에는 백엔드와 인프라에 올인
        description: | 
            - 새로운 것들 나올 때마다 이게 무엇이구나 정도는 보는 수준 (트렌드를 챙기는 편)
            - Webpack - package.json 보면서 구동 이해
            - 코드 따라가며 간단한 수정 정도는 가능한 정도
      - layout: left
        title: Miscellaneous
        quote: >
          기타 등등 - 만들거나 경험한 것들
        description: | 
            - Slack Bot 개발
            - Private Nuget Server 개발/운영
            - [SSO] IdentityServer4로 OAuth2 기반 인증
  
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
